### ISSUE TITLE
Serving multiple variants

### ISSUE THREAD

**Issue by henningbra** [KalvadTech/django-cloudflare-images#3]
May I ask how to serve more than one variant, using a list of [small, medium, large] preregistered variants in Cloudflare Images. How to manipulate the url?

**Comment by hnb2** [comment]
Hello @henningbra just to clarify you wish to serve 3 different variants off the same field ? Or you need 3 fields each with its own variant ?

Let me know

**Comment by henningbra** [comment]
Former

**Comment by henningbra** [comment]
Below property works. It would be possible to make a template tag passing in a variable from the below.
```
    @property
    def url_custom(self, variant='custom'):
        return f'{self.image.url.rsplit("/", 1)[0]}/{variant}'
```
Id that's the cleanest I will proceed.

**Comment by hnb2** [comment]
Hi @henningbra I think in your case, the best would be to add either:

 * 3 functions in your model, like `get_small_image_url` so you can avoid parameters
  * a single function with a parameter and add a templatetag as you suggested
  
  Both would work in a template

**Comment by hnb2** [comment]
So there is a method `url_with_variant` [here](https://github.com/KalvadTech/django-cloudflare-images/blob/main/cloudflare_images/storage.py#L108) defined in the Storage which is used in `url` [here](https://github.com/KalvadTech/django-cloudflare-images/blob/main/cloudflare_images/field.py#L32) in the Field. So Maybe in this field we could add a method which allows to pass a parameter to make it 100% dynamic.
