### ISSUE TITLE
Is there a way to change the URL with parameters? 

### ISSUE THREAD

**Issue by cyb3rs3ntry** [KalvadTech/django-cloudflare-images#5]
I'd like to remove the /public and add some parameters like w=128 and some other options for cloudflare. Is this best done in the template or is there a way to do it with this plugin?

**Comment by cyb3rs3ntry** [comment]
I appreciate the reply! I am really trying to make smaller images and with /public automatically appended the parameters like w=128 doesn't automatically resize the image. Does that make sense? I was thinking I could set a custom property on the model that would strip /public and apply the parameter, but thought there might be an easier way here.

**Comment by hnb2** [comment]
Hey @cyb3rs3ntry can you just confirm that you use this Cloudflare product: https://developers.cloudflare.com/images/cloudflare-images/serve-images/

Because when you mention query string parameters, i think you might be using something else like R2 or Cloudflare Workers.

**Comment by cyb3rs3ntry** [comment]
I can confirm I am am using that project. Maybe I'm using the wrong terminology but with cloudflare-images you can dynamicaly adjust the images based on the parameters. Example: 

150px version: https://imagedelivery.net/qQcI7UIamU8F_7NGHl_vww/c09e957e-3a00-4a76-af83-d2e4b90b1600/150px

public shoe: https://imagedelivery.net/qQcI7UIamU8F_7NGHl_vww/c09e957e-3a00-4a76-af83-d2e4b90b1600/public

or you can do https://imagedelivery.net/qQcI7UIamU8F_7NGHl_vww/c09e957e-3a00-4a76-af83-d2e4b90b1600/w=200px

and make w= whatever you want the size to be.

**Comment by hnb2** [comment]
Ah ok I understand now, you are using Flexible variants: https://developers.cloudflare.com/images/cloudflare-images/transform/flexible-variants/

This is usually recommended if you really need a lot of customization (see the warning on the page I linked above), its better to go through "regular" variants. You can now have up to 100 of those.

But regardless:

A) If your flexible variants are "static" (hardcoded), I suggest you just use this:

```python
from cloudflare_images.field import CloudflareImagesField
from django.db import models

class MyModel(models.Model):
   image = CloudflareImagesField(variant="w=200px")
```

B) If it's dynamic (the value of your w/h/anything depends on a parameter), you should have a look at this closed ticket: https://github.com/KalvadTech/django-cloudflare-images/issues/3. The idea is to have a property modifying the `url` property of the field to do whatever you want with it.

Hope it helps !
